version: '2.1'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data-mysql:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "event"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  streamsets:
    image: streamsets/datacollector
    restart: on-failure
    ports:
      - "18630:18630"
    volumes:
      - data-streamsets:/data

volumes:
  data-mysql:
  data-streamsets:
